config/routes.rb
Rails.application.routes.draw do
  resources :dreams
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
 
get "/home", to: "home#index"
root "home#index"



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dream.rb
class Dream < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :dreams
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  before_action :set_dream, only: [:show, :edit, :update, :destroy]

  # GET /dreams
  # GET /dreams.json
  def index
    @dreams = current_user.dreams
  end

  # GET /dreams/1
  # GET /dreams/1.json
  def show
  end

  # GET /dreams/new
  def new
    @dream = current_user.dreams.new
  end

  # GET /dreams/1/edit
  def edit
  end

  # POST /dreams
  # POST /dreams.json
  def create
    @dream = current_user.dreams.new(dream_params)

    respond_to do |format|
      if @dream.save
        format.html { redirect_to @dream, notice: 'Dream was successfully created.' }
        format.json { render :show, status: :created, location: @dream }
      else
        format.html { render :new }
        format.json { render json: @dream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dreams/1
  # PATCH/PUT /dreams/1.json
  def update
    respond_to do |format|
      if @dream.update(dream_params)
        format.html { redirect_to @dream, notice: 'Dream was successfully updated.' }
        format.json { render :show, status: :ok, location: @dream }
      else
        format.html { render :edit }
        format.json { render json: @dream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dreams/1
  # DELETE /dreams/1.json
  def destroy
    @dream.destroy
    respond_to do |format|
      format.html { redirect_to dreams_url, notice: 'Dream was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dream
      @dream = current_user.dreams.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dream_params
      params.require(:dream).permit(:date, :location)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/views/dream/_form.html.erb
<%= form_with(model: dream, local: true) do |form| %>
  <% if dream.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dream.errors.count, "error") %> prohibited this dream from being saved:</h2>

      <ul>
      <% dream.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dream/edit.html.erb
<h1>Editing Dream</h1>

<%= render 'form', dream: @dream %>

<%= link_to 'Show', @dream %> |
<%= link_to 'Back', dreams_path %>

app/views/dream/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dreams</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Location</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dreams.each do |dream| %>
      <tr>
        <td><%= dream.date %></td>
        <td><%= dream.location %></td>
        <td><%= dream.user.email %></td>
        <td><%= link_to 'Show', dream %></td>
        <td><%= link_to 'Edit', edit_dream_path(dream ) %></td>
        <td><%= link_to 'Destroy', dream, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dream', new_dream_path %>

app/views/dream/new.html.erb
<h1>New Dream</h1>

<%= render 'form', dream: @dream %>

<%= link_to 'Back', dreams_path %>

app/views/dream/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @dream.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @dream.location %>
</p>

<p>
  <strong>User:</strong>
  <%= @dream.user.email %>
</p>

<%= link_to 'Edit', edit_dream_path(@dream) %> |
<%= link_to 'Back', dreams_path %>

app/views/dreams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dreams</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Location</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dreams.each do |dream| %>
      <tr>
        <td><%= dream.date %></td>
        <td><%= dream.location %></td>
        <td><%= dream.user %></td>
        <td><%= link_to 'Show', dream %></td>
        <td><%= link_to 'Edit', edit_dream_path(dream) %></td>
        <td><%= link_to 'Destroy', dream, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dream', new_dream_path %>

app/views/home/index.html.erb
<h1> Welcome to my app </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DreamUp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body  class="<%= controller_name %> <%= action_name %>">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>

    <h2>Welcome <%= current_user.email %></h2>
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
    <%= link_to 'Change Password', edit_user_registration_path %>

  <% else %>

    <%= link_to "Sign Up", new_user_registration_path %>
    <%= link_to "Sign In", new_user_session_path %>

  <% end %>
    <%= yield %>
  </body>
</html>